### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by yvi1** [VoigtLab/dnaplotlib#11]
Hi Thomas et al.,

I finally got to use DNAplotlib. Very cool app. I have a suggestion to quick.py, if you don't mind:

Currently, quick.py is executed this way:

`python quick.py -input "p.gray i.lightblue r.lightred c.green t.orange -t.purple -c.black -r.yellow -p.yellow" -output out.pdf`

a user passes **orientation**, **part type**, and **color** in the list of parameters.

**SUGGESTION:**
It would be very useful if a user could also pass **optional** part instance:

`python quick.py -input "p1.gray i1.lightblue r1.lightred c2.green t1.orange t1.purple c1.black r1.yellow p1.yellow" -output out.pdf`

and the program would parse those part instances and generate corresponding labels under each part on the PDF image:
"p1" or "i1" or "cds2" (or "g2") e.t.c. If user did not provide part instance, then label won't be generated.

P.S. in the description, it doesn't say that the image can also be saved as .png
`-output out.png`

@chofski 

Cheers,
-Y

**Comment by chofski** [comment]
Hi Yury, interesting suggestion and we'll look into getting that added as it won't break any of the existing functionality. I'll also update the description to give the range of file formats. Basically, any extension supported by matplotlib can be used so there is a huge range to choose from.

**Comment by yvi1** [comment]
Hi Thomas,

Did you have a chance to implement or think about adding this to quick.py? I have a good use case for this addition in my tool that uses DNAPlotlib as a plotting service.

Regards,
-Yury

**Comment by chofski** [comment]
Hi Yury, sorry my focus has been on the major update to the software that will likely take place early next year, but from looking at this request it shouldn't be difficult to implement. I'm confused though by what precisely the labels need to be? Could you write a couple simple example calls and what you would expect to be rendered. Thanks, Tom,

**Comment by chofski** [comment]
Hi Yury,

I've updated the `quick.py` app to now allow for a label (this must not contain a space) to be included:

`python quick.py -input "p.P1.red r.black c.CDS1.blue t.black" -output output.png`

This produces the following image:

![output](https://user-images.githubusercontent.com/345333/31014904-28b7d344-a515-11e7-9337-a348fef8f757.png)

I will close the issue as this should solve your problem. If not feel free to reopen.
