### ISSUE TITLE
Arc height not changing with regulation type connection

### ISSUE THREAD

**Issue by michael1788** [VoigtLab/dnaplotlib#15]
In the example of the [recombinase_not_gate.py](https://github.com/VoigtLab/dnaplotlib/tree/master/gallery/recombinase_not_gate), I'm trying to get the arc to be lower because they overlay the sequence from above in the figure for sequences longer than in the example.  

However, despite changing the arc_height argument, the height isn't changing, and I haven't been successful at finding why. When changing arc_height in the [xnor_truthtable.py](https://github.com/VoigtLab/dnaplotlib/tree/master/gallery/xnor_truthtable) example, it's working.   

I'm using python 3.6.1 and matplotlib 2.0.2

**Comment by Dyex719** [comment]
Try changing the values of the attributes `arc_height_start` and `arc_height_end` when you are creating the arc. 
(https://github.com/VoigtLab/dnaplotlib/blob/master/gallery/recombinase_not_gate/recombinase_not_gate.py#L237#L238)
Notice how if I change the `arc_height_start` and `arc_height_end` values of arc2 from 10 and 10 to 15 and 15, the arc moves down slightly.

![1](https://user-images.githubusercontent.com/30334566/37866425-a508e994-2fb0-11e8-9a25-674d6116d47d.png)

![2](https://user-images.githubusercontent.com/30334566/37866426-a53e16f0-2fb0-11e8-8a0a-073c1e05aa74.png)

I'm using python 3.6.0 and matplotlib 2.0.2
Hope this helps :)
