### ISSUE TITLE
Support of new symbols (SBOL Visual 2.0)

### ISSUE THREAD

**Issue by mcrone** [VoigtLab/dnaplotlib#16]
Thank you for the great tool! Will the glyphs be updated with the latest symbols for SBOL visual 2.0? I am particularly interested in the binding sites and non-coding sequence glyphs.

**Comment by chofski** [comment]
Hi, yes we are in the process of completely rewriting the library to allow for better management of glyphs, including full support for SBOLv2 and immediate inclusion of any new glyphs. We'll also be able to handle modules and hierarchy much better. This is likely to be released in the next couple months so hopefully you can hold out until then.
