### ISSUE TITLE
Adjusting Figure Parameters

### ISSUE THREAD

**Issue by TBWarrington** [VoigtLab/dnaplotlib#17]
I am curious how to do a few things or suggesting features if they aren't currently possible.

First: Adjusting title spacing on the variants library
I tried out the variants library script but it's cutting off my titles and I can't figure out how to fix it. Even better would be to adjust it dynamically with title name.
![variants_library](https://user-images.githubusercontent.com/4634846/41490895-584af914-70b3-11e8-9b14-202b02d06c0e.png)

Second: Adjust y-spacing on library_plot script
Again I tried out the library_plot but the spacing between the constructs is huge and I can't seem to reduce it without cutting off the regulation info.
![test1](https://user-images.githubusercontent.com/4634846/41490665-55fadef0-70b2-11e8-9403-cfa56140125a.png)

I was also wondering if there is a convenient way to have multiple bars for each construct for the performance data on the variants library type script. It would be nice to be able to show induced and un-induced data. I assume it must be possible but I haven't torn into the script enough to figure it out yet.

Also, is there a way to produce a figure legend? Either as part of the figure or as a separate png would be helpful. I'm testing out RBS variants and it would be helpful to show what the colours mean.

Finally, is there a way to show regulation by environmental factors or factors on a different "chromosome"? 

Thanks, for your help.
This library is pretty awesome so please keep up the fantastic work.

**Comment by chofski** [comment]
A lot of questions there!

For the variant library plotter, all the changes you require are possible, but will require you editing the Python script directly. If you are familiar with matplotlib this shouldn't be a problem and it will really allow you to get the most out of the library. 

For the library_plot question, again the script tries to be clever, but doesn't always do so well. This is normally if the ratio (height to width) is different than what it is used to. Again, if you play with the fig_x_dim and fig_y_dim on lines 236-239, you'll be able to get around the problem.

For regulation across "chromosomes" we don't support this at present, but are in the process of finishing development on version 2.0, which will allow for this.
