### ISSUE TITLE
What is the "circle-X" glyph?

### ISSUE THREAD

**Issue by jakebeal** [VoigtLab/dnaplotlib#22]
I see there is a glyph offered by DNAplotlib that is a circle with an X inside of it. What is that intended to represent?  If it's useful, I'd like to import it into SBOL Visual.

**Comment by chofski** [comment]
I assume you mean the "spacer" element that is used in a couple papers like: https://science.sciencemag.org/content/352/6281/aac7341.long . No problem with it being incorporated into SBOL Visual.

**Comment by jakebeal** [comment]
Note that this has gotten pulled into the discussion in https://github.com/SynBioDex/SBOL-visual/issues/34, and we have now gotten an official SO term for this: SO:0002223 "inert DNA spacer".

We still need an SEP to officially incorporate it.

**Comment by chofski** [comment]
Will add to my list of TODOs at HARMONY.
