### ISSUE TITLE
API Docs

### ISSUE THREAD

**Issue by multimeric** [VoigtLab/dnaplotlib#24]
I've been reading the source code and the example scripts for documentation of all the plot fields (things like `label`, `label_y_offset`, `label_size` etc.). Are these documented somewhere?

**Comment by chofski** [comment]
They are mentioned in the associated publication (https://pubs.acs.org/doi/10.1021/acssynbio.6b00252) but are currently not fully documented. This will be addressed in v2.0 that will include a full API document.
