### ISSUE TITLE
Proportional sizes of features

### ISSUE THREAD

**Issue by mandel01** [VoigtLab/dnaplotlib#30]
I am trying to plot genes proportional to their sizes in a genome and encountering some issues. I noticed that the same issue occurs in the [`input_gff`](https://github.com/VoigtLab/dnaplotlib/tree/master/gallery/input_gff) example, where all of the genes are plotted similar in size even though the GFF file specifies that gene C should be almost twice the size of gene A (1563 nt vs 882 nt). I'd appreciate any feedback on whether I'm interpreting things wrong or whether this may be a bug. Thanks for this cool library!!

**Comment by chofski** [comment]
This is not an error in the example, it is merely not designed to handle this. There are other examples that show how the length parameter can be altered inline with the actual gene length. See for example: https://github.com/VoigtLab/dnaplotlib/tree/master/gallery/input_bed

**Comment by mandel01** [comment]
@chofski Thanks for the reply and great software here!
