### ISSUE TITLE
Aptamer SBOL symbol

### ISSUE THREAD

**Issue by mcrone** [VoigtLab/dnaplotlib#7]
Is there a symbol for an aptamer? I have seen something about an aptamer symbol in the SBOL visual working group on google groups but couldn't find it here.
[https://groups.google.com/forum/#!msg/sbol-visual/7LGWdo0NGqs/oXFLnEFFtMsJ](url)

**Comment by chofski** [comment]
That symbol hasn't made it into the SBOLv standard yet, but will look into getting it added to the current set we support.
