### ISSUE TITLE
RNA Fusions

### ISSUE THREAD

**Issue by jasper1918** [VoigtLab/dnaplotlib#9]
Came across your package and was wondering if there are defined workflows for plotting a gene fusion. Is this possible or potentially possible with some minimal dev work on my end?

**Comment by chofski** [comment]
If you are considering a 5'-tag then you could use an 'sbol_user_defined' element and correct the normal right and left spacing of the the tag and CDS to attach it. You could also think about using a similar approach on the other end, but it will be difficult to make it part of the arrow head at present. I think SBOLv might be including a tag element in the future that we will support asap.

**Comment by chofski** [comment]
The other option we recently used in a diagram was to overlay two CDS elements (i.e. have negative left padding on the second CDS to make it overlap with the preceding one. The 'zorder' parameter of these elements can then be altered to make sure you see the correct outcome.
